### ISSUE TITLE
Naming of package and repo

### ISSUE THREAD

**Issue by rufuspollock** [datasets/historical-income-households-us#1]
To be more consistent with traditional naming I suggest:

```
household-income-us-historical
```

Why? Household-income is the actual indicator and the the historical is a time indicator - see https://datahub.io/docs/data-packages/publish-faq#data-package-name for existing conventions (that we could update).

**Comment by anuveyatsu** [comment]
I've renamed the package and all related properties in the `datapackage.json` and `flow.yaml` files. @Mikanebu can you please rename the repository as I don't have permission to do so. 

Thanks!

**Comment by Mikanebu** [comment]
@anuveyatsu updated to `household-income-us-historical` and republished https://datahub.io/core/household-income-us-historical

**Comment by rufuspollock** [comment]
FIXED.
